import sys
import os

P = '\x1b[1;97m' # PUTIH
M = '\x1b[1;91m' # MERAH
H = '\x1b[1;92m' # HIJAU
B = '\x1b[1;94m' # BIRU
N = '\x1b[0m' # WARNA MATI
K = '\x1b[1;93m' # KUNING

if sys.platform.startswith("win"):
    "WINDOWS"
    print(f"\n{K}Installing the python modules required for the DarkStar Tool:")
    os.system("pip install --upgrade pip")
    os.system("pip install --upgrade pip setuptools wheel")
    os.system("pip install names")
    os.system("pip install aiohttp")
    os.system("pip install time")
    os.system("pip install rich")
    os.system("pip install colorama")
    os.system("pip install requests")
    os.system("pip install json")
    os.system("pip install random")
    os.system("pip install webbrowser")
    os.system("pip install holehe")
    os.system("pip install base64")
    os.system("pip install threading")
    os.system("pip install psutil")
    os.system("pip install bs4")
    os.system("pip install googlesearch")
    os.system("pip install itertools")
    os.system("pip install phonenumbers")
    os.system("pip install pystyle")
    os.system("pip install pytube")
    os.system("pip install httpx")
    os.system("pip install stdiomask")
    os.system("pip install pytube")
    os.system("pip install cryptography")
    os.system("pip install pycryptodome")
    os.system("pip install pywin32")
    print("Finish.")
    os.system("python DarkStar.py")

elif sys.platform.startswith("linux"):
    "LINUX"
    print(f"\n{M}[{P}01{M}] {B}Termux\n{M}[{P}02{M}] {B}Kali Linux")
    p = input(f"\n{M}[{P}+{M}] {B}Pilih :{P} ")
    if p in["01","1"]:
        print(f"\n{K}Installing the python modules required for the DarkStar Tool:{N}")
        os.system('pkg update && apt upgrade')
        os.system('pkg install golang')
        os.system('pkg install nodejs-lts')
        os.system('pkg install perl')
        os.system('pkg install git')
        os.system('pkg install neofetch')
        os.system('apt install wget')
        os.system("pip3 install --upgrade pip")
        os.system("pip3 install --upgrade pip setuptools wheel")
        os.system("pip3 install names")
        os.system("pip3 install aiohttp")
        os.system("pip3 install time")
        os.system("pip3 install rich")
        os.system("pip3 install colorama")
        os.system("pip3 install requests")
        os.system("pip3 install holehe")
        os.system("pip3 install psutil")
        os.system("pip3 install bs4")
        os.system("pip3 install phonenumbers")
        os.system("pip3 install pystyle")
        os.system("pip3 install pytube")
        os.system("pip3 install httpx")
        os.system("pip3 install stdiomask")
        os.system("pip3 install os-sys")
        os.system("pip3 install pycryptodome")
        os.system("pip3 install pywin32")
        os.system('pip3 install google')
        os.system('pip3 install colorama')
        os.system('pip3 install wget')
        os.system('pip3 install requests')
        os.system('pip3 install sockets')
        os.system('pip3 install pythonping')
        os.system('pip3 install os-sys')
        os.system('pip3 install times')
        os.system('pip3 install sys')
        os.system('pip3 install ipaddress')
        os.system('pip3 install pyexiftool')
        os.system('pip3 install beautifulsoup4')
        os.system('pip3 install phonenumbers')
        os.system('pip3 install faker')
        os.system('pip3 install urllib3')
        os.system('pip3 install regex')
        os.system('pip3 install argparse')
        os.system('pip3 install random2')
        os.system('pip3 install importlib')
        os.system('pip3 install scapy')
        os.system('pip3 install cloudscraper')
        os.system('pip3 install googlesearch')
        os.system('pip3 install bs4 mechanize')
    
        print(f"{H}Finish.")
        os.system("python3 DarkStar.py")
 
    elif p in["02","2"]:
        print(f"\n{K}Installing the python modules required for the DarkStar Tool:{N}")
        os.system('apt update && apt upgrade')
        os.system('apt install golang')
        os.system('apt install nodejs-lts')
        os.system('apt install perl')
        os.system('apt install git')
        os.system('apt install neofetch')
        os.system('apt install wget')
        os.system("pip3 install --upgrade pip")
        os.system("pip3 install --upgrade pip setuptools wheel")
        os.system("pip3 install names")
        os.system("pip3 install aiohttp")
        os.system("pip3 install time")
        os.system("pip3 install rich")
        os.system("pip3 install colorama")
        os.system("pip3 install requests")
        os.system("pip3 install json")
        os.system("pip3 install random")
        os.system("pip3 install string")
        os.system("pip3 install holehe")
        os.system("pip3 install base64")
        os.system("pip3 install threading")
        os.system("pip3 install psutil")
        os.system("pip3 install bs4")
        os.system("pip3 install webbrowser")
        os.system("pip3 install itertools")
        os.system("pip3 install phonenumbers")
        os.system("pip3 install pystyle")
        os.system("pip3 install pytube")
        os.system("pip3 install httpx")
        os.system("pip3 install stdiomask")
        os.system("pip3 install cryptography")
        os.system("pip3 install pycryptodome")
        os.system("pip3 install pywin32")
        os.system('pip3 install google')
        os.system('pip3 install colorama')
        os.system('pip3 install wget')
        os.system('pip3 install requests')
        os.system('pip3 install sockets')
        os.system('pip3 install pythonping')
        os.system('pip3 install os-sys')
        os.system('pip3 install times')
        os.system('pip3 install sys')
        os.system('pip3 install ipaddress')
        os.system('pip3 install pyexiftool')
        os.system('pip3 install beautifulsoup4')
        os.system('pip3 install phonenumbers')
        os.system('pip3 install faker')
        os.system('pip3 install urllib3')
        os.system('pip3 install regex')
        os.system('pip3 install argparse')
        os.system('pip3 install random2')
        os.system('pip3 install importlib')
        os.system('pip3 install scapy')
        os.system('pip3 install cloudscraper')
        os.system('pip3 install googlesearch')
        os.system('pip3 install bs4 mechanize')
    
        print(f"{H}Finish.")
        os.system("python3 DarkStar.py")
    else:
        print(f"{M}Input Yang Anda Masukkan Salah!!")
        exit()